### ISSUE TITLE
Pagination with blaze - each iteration

### ISSUE THREAD

**Issue by TomokoOG** [Navybits/meteor-pagination#10]
Hi, 

I have user-created documents which I iterate like so: 

```
   {{#each characters}}
    <li>
      <a href="/c/{{name}}"><img src="{{mainImg}}"></a>
      {{name}}
    </li>
     {{/each}}
```
But since on this site all documents that characters-collection has will be displayed I wanted to stack them by 20 per site with pagination. 

I tried it like so
**new_characters.js**
```
Template.new_characters.helpers({
  dataToPaginate() {
    //return your data as an array of objects
    return Characters.find({isNpc: false}, {sort: {createdAt: -1}});
 },
})
```
**new_characters.html**
```
{{#navybitsPagination data=dataToPaginate}}
    <div>Name : {{name}} </div> <br>
{{/navybitsPagination}}
```
But this it not how it works. It just shows an interation of "Name :". My questions are: How could I iterate those characters-documents and how could I determine how many documents per page are displayed?

Thanks!

**Comment by tahaziadeh** [comment]
Hello @TomokoOG , 
Thank you for reporting your issue, actually the data parameter in `navybitsPagination` helper expects an array of data not a cursor. Try this instead:
**new_characters.js**
```
Template.new_characters.helpers({
  dataToPaginate() {
    //return your data as an array of objects
    return Characters.find({isNpc: false}, {sort: {createdAt: -1}}).fetch();
 },
})
```
Plus, in order to iterate over the data, you have to write your publication on the server like :
```
Meteor.publish(“charactersPublication”, function (options) {
 let limit = options.limit || 10;
 return Characters.find({isNpc: false}, {limit:limit, sort: {createdAt: -1}});
})

```
Then pass the publication name like the following 
**new_characters.html**
```
{{#navybitsPagination data=dataToPaginate subscriptionDetails=subscriptionDetails}}
    <div>Name : {{name}} </div> <br>
{{/navybitsPagination}}
```
**new_characters.js**
```
Template.new_characters.helpers({
//....
subscriptionDetails() {
   return {
     subscriptionName: “charactersPublication”
   };
 },
//.....
})
```
