### ISSUE TITLE
Sorting?

### ISSUE THREAD

**Issue by fpreti** [Navybits/meteor-pagination#11]
Hi @tahaziadeh ,
can you explain me how to sort?i tried to set {{#navybitsPagination data=dataToPaginate perPage=6 isTable=true **sortingBy='data'**}} but not working.

Thanks,
Francesco

**Comment by tahaziadeh** [comment]
Hi @fpreti ,
Thank you for posting you question.
Actually, the sorting is out of scope for this module. And it should be!
The template `navybitsPagination` represents a bridge that allows you to paginate whatever data you provide in the `data` attribute.
You can sort your data first in your helper then send it to the template.

Taha
