### ISSUE TITLE
Template level subscription

### ISSUE THREAD

**Issue by varunlakshmaiah** [Navybits/meteor-pagination#4]
Hello How can I subscribe only at template level .... your pagination uses Meteor.subscribe for subscription instead how can I use this.subscribe() to subscribe..?

**Comment by tahaziadeh** [comment]
Hello @varunlakshmaiah,
Thank you for reporting .. The template level subscription is not supported by this package. However, in case it makes sense to be there, we can collaborate and enhance the implementation as per needed.
Kindly provide more details about your need. This way I can figure out what kind of change I have to elaborate.

**Comment by varunlakshmaiah** [comment]
Hi @tahaziadeh Please verify #6 and merge it.

**Comment by varunlakshmaiah** [comment]
Fixed with #6
