### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by shaunstoltz** [Navybits/meteor-pagination#5]
Cannot get this working... some documentation would be nice, or actual working code.

**Comment by shaunstoltz** [comment]
yeah, no idea... let me know when this thing actually works.

**Comment by hstabbal** [comment]
Did you follow the blog post here : 
https://blog.navybits.com/efficient-and-high-performance-pagination-in-meteor-bb5d379d234

**Comment by shaunstoltz** [comment]
My fault, sorry.

**Comment by hstabbal** [comment]
No pb.
