### ISSUE TITLE
onCreated and onRendered Callback for pagination

### ISSUE THREAD

**Issue by varunlakshmaiah** [Navybits/meteor-pagination#7]
It will be very helpful if you want to execute some function after pagination is rendered or created..?
What do you think about it.?

**Comment by tahaziadeh** [comment]
Thank you for your contribution @varunlakshmaiah 
We can add support for params such as onCreated and onRendered. Unfortunately, we are currently not spending lot to improve this package. However, any pull request that aims to improve is most welcome.

**Comment by varunlakshmaiah** [comment]
@tahaziadeh Ha Ok I will some time to imporove the package :+1:
