### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by antonio-goncalves-unp** [Navybits/meteor-pagination#8]
How to use this library as a React component? I was trying using this to create a wrapper containing the meteor-pagination, but I am having some difficults.

https://github.com/gadicc/meteor-blaze-react-component

**Comment by tahaziadeh** [comment]
Hello @antonio-goncalves, thank you for reporting the issue.
The documentation has been updated to indicates how to use this package with react

**Comment by antonio-goncalves-unp** [comment]
Thanks
