### ISSUE TITLE
Materialize is not supported error message- because of the Materialize is upgraded

### ISSUE THREAD

**Issue by RobinJiao** [Navybits/meteor-pagination#9]
Really appreciate this great pagination - super easy to use. 
when i run the package in my app, find 2 console error messages - the pagination still works fine just console message :
i think it just because of the Materialize upgrade and change the select init to  " $('select').formSelect() ;  " not "$('select').material_select();" anymore.

the below is the code reporting error.
    //checking if the project has materialize
    try {
        $('select').material_select();
    } catch (error) {
        console.log('Materialize is not supported!');
    }

**Comment by tahaziadeh** [comment]
Hello @RobinJiao,
Thank you for reporting this and sorry for the late reply.
By default, the module has optimized ui when using the materialize lib. The ui will break if you don't have Materialize as a dependancy. However, you may need it working anyway without ui optimization.
The logs in the browser are meant to warn you about this constraint.
